# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matching.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'matching.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ematching.proto\x12\x08matching\"\x84\x01\n\x12SubmitOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x0c\n\x04side\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x01\x12\x10\n\x08quantity\x18\x07 \x01(\x03\"\xb7\x01\n\x0bTradeResult\x12\x10\n\x08trade_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x14\n\x0c\x62uy_order_id\x18\x03 \x01(\t\x12\x15\n\rsell_order_id\x18\x04 \x01(\t\x12\x10\n\x08\x62uyer_id\x18\x05 \x01(\t\x12\x11\n\tseller_id\x18\x06 \x01(\t\x12\r\n\x05price\x18\x07 \x01(\x01\x12\x10\n\x08quantity\x18\x08 \x01(\x03\x12\x13\n\x0b\x65xecuted_at\x18\t \x01(\t\"\x81\x01\n\x13SubmitOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06\x66illed\x18\x03 \x01(\x03\x12\x11\n\tremaining\x18\x04 \x01(\x03\x12%\n\x06trades\x18\x05 \x03(\x0b\x32\x15.matching.TradeResult\"6\n\x12\x43\x61ncelOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\"7\n\x13\x43\x61ncelOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x10OrderBookRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"-\n\nPriceLevel\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x10\n\x08quantity\x18\x02 \x01(\x03\"k\n\x11OrderBookResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\"\n\x04\x62ids\x18\x02 \x03(\x0b\x32\x14.matching.PriceLevel\x12\"\n\x04\x61sks\x18\x03 \x03(\x0b\x32\x14.matching.PriceLevel2\xf2\x01\n\x0fMatchingService\x12J\n\x0bSubmitOrder\x12\x1c.matching.SubmitOrderRequest\x1a\x1d.matching.SubmitOrderResponse\x12J\n\x0b\x43\x61ncelOrder\x12\x1c.matching.CancelOrderRequest\x1a\x1d.matching.CancelOrderResponse\x12G\n\x0cGetOrderBook\x12\x1a.matching.OrderBookRequest\x1a\x1b.matching.OrderBookResponseB!Z\x1fquantflow/matching-engine/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matching_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037quantflow/matching-engine/proto'
  _globals['_SUBMITORDERREQUEST']._serialized_start=29
  _globals['_SUBMITORDERREQUEST']._serialized_end=161
  _globals['_TRADERESULT']._serialized_start=164
  _globals['_TRADERESULT']._serialized_end=347
  _globals['_SUBMITORDERRESPONSE']._serialized_start=350
  _globals['_SUBMITORDERRESPONSE']._serialized_end=479
  _globals['_CANCELORDERREQUEST']._serialized_start=481
  _globals['_CANCELORDERREQUEST']._serialized_end=535
  _globals['_CANCELORDERRESPONSE']._serialized_start=537
  _globals['_CANCELORDERRESPONSE']._serialized_end=592
  _globals['_ORDERBOOKREQUEST']._serialized_start=594
  _globals['_ORDERBOOKREQUEST']._serialized_end=628
  _globals['_PRICELEVEL']._serialized_start=630
  _globals['_PRICELEVEL']._serialized_end=675
  _globals['_ORDERBOOKRESPONSE']._serialized_start=677
  _globals['_ORDERBOOKRESPONSE']._serialized_end=784
  _globals['_MATCHINGSERVICE']._serialized_start=787
  _globals['_MATCHINGSERVICE']._serialized_end=1029
# @@protoc_insertion_point(module_scope)
